[package]
name = "nes-emulator-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3"
egui_glow = "0.15.0"
imgui-sdl2 = "0.14.0"
sdl2 = "0.34"
imgui = "0.7"
gl = "0.10.0"
imgui-opengl-renderer = "0.11"

[profile.release]
debug = true